### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by stoddabr** [TedisAgolli/nextjs-routes-docs-generator#4]
Running this on a typescript project causes the following error: `[ERROR] Unexpected token (26:12)`

The full error being thrown is:
`SyntaxError: Unexpected token (36:5)
    at Parser.pp$4.raise (/PATH-TO-PROJECT-DIR/node_modules/acorn/dist/acorn.js:3459:15)
    at Parser.pp$9.unexpected (/PATH-TO-PROJECT-DIR/node_modules/acorn/dist/acorn.js:760:10)
    at Parser.pp$9.expect (/PATH-TO-PROJECT-DIR/node_modules/acorn/dist/acorn.js:754:28)
    at Parser.pp$7.parseBindingList (/PATH-TO-PROJECT-DIR/node_modules/acorn/dist/acorn.js:2026:19)
    at Parser.pp$8.parseFunctionParams (/PATH-TO-PROJECT-DIR/node_modules/acorn/dist/acorn.js:1368:24)
    at Parser.pp$8.parseFunction (/PATH-TO-PROJECT-DIR/node_modules/acorn/dist/acorn.js:1357:10)
    at Parser.pp$8.parseExport (/PATH-TO-PROJECT-DIR/node_modules/acorn/dist/acorn.js:1669:33)
    at Parser.pp$8.parseStatement (/PATH-TO-PROJECT-DIR/node_modules/acorn/dist/acorn.js:936:76)
    at Parser.pp$8.parseTopLevel (/PATH-TO-PROJECT-DIR/node_modules/acorn/dist/acorn.js:817:23)
    at Parser.parse (/PATH-TO-PROJECT-DIR/node_modules/acorn/dist/acorn.js:589:17) {
  pos: 907,
  loc: Position { line: 36, column: 5 },
  raisedAt: 908
}`

Digging further, it appears that the acorn parser doesn't natively support typescript but there are some spin-off projects that do. 

Is there any interest in updating this to support typescript or should I make my own fork of this project?

**Comment by TedisAgolli** [comment]
Merged an attempt at handling Typescript. Let me know if it fixes your issue and then I'll publish the update!

**Comment by grooney** [comment]
Has there been any luck on fixing this to support Typescript? I'm trying to use this package for a NextJs 13 app written in TS and am getting  [ERROR] Unexpected token (4:26) from acorn

**Comment by TedisAgolli** [comment]
I did release a version that _should_ support Typescript but apparently it didn't work. The latest version is using a new parser so could you give that a try?
